[tox]
envlist = lint, py311
skipsdist = true

[testenv]
deps = -rrequirements.txt
commands =
    pytest tests/specs --alluredir=allure-results

[testenv:lint]
deps = -rrequirements.txt
commands =
    flake8 tests
